package com.redhat.syseng.businessautomation.cep.test

import io.cloudevents.CloudEvent
import com.redhat.syseng.businessautomation.cep.model.Result

declare CloudEvent
  @role( event )
end

rule R1
  when
    $r : Result()
    $e : CloudEvent()
    Number(intValue > 2) from accumulate($c: CloudEvent(this != $e, this meets[5s] $e), count($c))
  then
    System.out.println("We have two events" + " 5 seconds apart");
    $r.setValue("e2 was at least 5s after e1");
end
